name: ne_countries_grpc
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  bloc: ^8.1.4
  # build_grpc_channel: ^0.5.0
  build_context: ^3.0.0
  dart_jts: null
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_map: null
  freezed_annotation: null
  grpc: ^4.0.0
  intl: 0.19.0
  latlong2: ^0.9.1
  rxdart: ^0.28.0
  url_launcher: ^6.3.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: null
  flutter_test:
    sdk: flutter
  freezed: null
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

scripts:
  build: fvm flutter pub run build_runner build --delete-conflicting-outputs
  watch: fvm flutter pub run build_runner watch --delete-conflicting-outputs
  buildapp: fvm flutter build appbundle
  test: fvm flutter test
